### ISSUE TITLE
When Chosen One event is failed, player cannot receive event again

### ISSUE THREAD

**Issue by Peacevan101** [Peacevan101/SundownStellarisMod#1]
### Details
When reaching into the shroud, game decides which event player will receive.

After failing the Chosen One event, modifier is set such that the Chosen One event cannot be selected when rolling for the shroud event.

**Comment by Spyboticsguy** [comment]
Was not able to replicate. Examination of the relevant file, [utopia_shroud_events.txt](https://github.com/Peacevan101/SundownStellarisMod/blob/febe97823de3affa30717d7d47cbecfbf9ad7a20/events/utopia_shroud_events.txt), shows no modifier which should prevent the chosen one event from being selected again.

**Comment by Spyboticsguy** [comment]
@Peacevan101 can you replicate? If not, going to close this for now.
